In [465]:
import numpy as np

# Numpy Arrays
- Numpy arrays essentially come in two flavors: vectors and matrices. 
- Vectors are strictly 1-dimensional arrays and matrices are 2-dimensional

In [466]:
mylist = [1, 2, 3]
mylist

[1, 2, 3]

In [467]:
np.array(mylist)

array([1, 2, 3])

In [468]:
my_matrix = [[1,2], [3,4]]
my_matrix

[[1, 2], [3, 4]]

In [469]:
np.array(my_matrix)

array([[1, 2],
       [3, 4]])

### Using built-in methods to generate Arrays

#### arange: return evenly spaced values within a given interval
#### - np.arange(start, stop, step, ...)
- start: the starting value of the sequence
- stop: the end value of the sequence
- step: the spacing between values
  
note: it will automatically adjust the how many values to generate

In [470]:
np.arange(0, 10) # starting from 0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [471]:
np.arange(0, 12, 2) # the 3rd parameter indicates the space between returning values

array([ 0,  2,  4,  6,  8, 10])

#### linspace: return evenly spaced numbers over a specified interval
#### - np.linspace(start, stop, num, ...)
- start: the starting value of the sequence
- stop: the end value of the sequence
- num: the number of values to generate

note: this will automatically determine how far apart to space the values

In [472]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [473]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### zeros and ones: generates arrays to zeroes or ones

In [474]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [475]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [476]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [477]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### eye: creates an identity matrix

In [478]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Random: Numpy has lots of ways to create random number arrays:

#### - rand: create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1]

In [479]:
np.random.rand(5)

array([0.50857238, 0.28181646, 0.24310239, 0.71944958, 0.15183299])

In [480]:
np.random.rand(3,3)

array([[0.61001817, 0.90487907, 0.85156981],
       [0.36548148, 0.99295377, 0.56193876],
       [0.56487902, 0.39604666, 0.1261353 ]])

#### - randn: return a sample (or samples) from the "standard normal" distribution. Unlike randon which is uniform

In [481]:
np.random.randn(5) # the randomly generated values are not limited over [0, 1]

array([ 0.47602453,  1.47782349, -0.6013046 ,  0.20606816, -0.06784239])

In [482]:
np.random.randn(3,3)

array([[ 0.19469576,  1.46770068, -1.77369932],
       [-0.26208571, -1.85738319, -1.65911038],
       [-0.58217518, -0.08884194,  0.81185247]])

#### - randint: return random integers from low(inclusive) to high(exclusive)
#### np.random.randint(low, high, size)
- low: lowest integer; but works as the highest integer if no highest integer
- high: highest integer (optional)
- size: output shape if it is an array (optional)

In [483]:
np.random.randint(10) # range [0 - 10)

0

In [484]:
np.random.randint(20, 50) # range [20 - 50)

41

In [485]:
np.random.randint(1, 50, 10) # array with range [1, 50)

array([40, 19, 16,  2, 30, 24,  6,  4,  1, 30])

In [486]:
np.random.randint(10, 50, (2,3)) # 2x3 array/matrix with range [10, 50)

array([[39, 48, 49],
       [13, 28, 15]])

### Array Attributes & Methods
#### - Reshape: returns an array containing the same original data with a new shape
note: it does not change the original array

In [487]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [488]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### - Shape: it is an attribute that arrays have (not a method)

In [489]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [490]:
arr.shape

(25,)

In [491]:
arr.reshape(5,5).shape

(5, 5)

In [492]:
arr.reshape(1,25).shape

(1, 25)

In [493]:
arr2 = np.random.randint(0, 10, (2,3))
arr2

array([[8, 7, 3],
       [1, 3, 7]])

In [494]:
arr2.shape

(2, 3)

In [495]:
arr2.reshape(3,2).shape

(3, 2)

#### - max, min, argmax, argmin:
useful methods for finding the max and min values, and find their corresponding index locations

In [496]:
randArr = np.random.randint(1, 50, 10)
randArr

array([46, 29, 23, 29, 22, 19, 49, 12, 33, 22])

In [497]:
print(randArr.max())
print(randArr.argmax())
print(randArr.min())
print(randArr.argmin())

49
6
12
7


#### - dtype: grab the data type of the object in the array

In [498]:
randArr.dtype

dtype('int64')

### Numpy Indexing and Selection

#### - Slicing
- Extracting subarrays from numpy arrays (similar to slicing Python lists)
#### array[start:stop:step]
- start: where the slice starts (inclusive)
- stop: where it ends (exclusive)
- step: how many indices to skip

- 1D Slicing

In [515]:
arr = np.array([10,20,30,40,50])

print(arr[:3])
print(arr[1:4])
print(arr[::2]) 
print(arr[::-1]) # in reverse order

[10 20 30]
[20 30 40]
[10 30 50]
[50 40 30 20 10]


- 2D Slicing

In [516]:
arr = np.array([[1,2,3], 
                [4,5,6], 
                [7,8,9]])

print(arr[0])       # equivalent to arr[0,:] -> slicing first rwo
print(arr[:1])      # second column of each row
print(arr[0:2,1:3]) # specifically slicing some elements

[1 2 3]
[[1 2 3]]
[[2 3]
 [5 6]]


##### Note: 
- Slicing gives you the view of the array, if you change the view, the array will be changed directly

In [517]:
arr = np.array([1,2,3,4,5])
sub = arr[0:3] # slicing elements at index 0-2
print(sub)
sub[0] = 100   # assign new value to sliced array
print(arr)     # the original array will be changed

[1 2 3]
[100   2   3   4   5]


- To have a independent copy of the array, using .copy()

In [518]:
arr = np.array([[1,2,3], [4,5,6]])
sub_copy = arr[1:3].copy()
sub_copy

array([[4, 5, 6]])

#### - Brackect Indexing and Selection

In [499]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [500]:
int(arr[5]) # get the value at the index

6

In [501]:
arr[1:5] # get the values which index are at the range [1, 5)

array([2, 3, 4, 5])

In [502]:
arr[0:5]

array([1, 2, 3, 4, 5])

#### - Indexing 2D Arrays (Matrices)

In [503]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [504]:
arr_2d[0] # indexing row

array([1, 2, 3])

In [505]:
arr_2d[:,2] # indexing column

array([3, 6, 9])

In [506]:
print(arr_2d[0][2])

3


#### - Fancy Indexing
- Allows you to select entire rows and columns out of order

In [507]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [508]:
arr[[0,2]] # indexing specific rows

array([[1, 2, 3],
       [7, 8, 9]])

In [509]:
# indexing in any order
arr[[2,0,1]]

array([[7, 8, 9],
       [1, 2, 3],
       [4, 5, 6]])

In [510]:
# indexing specific elements in any rows and columns
row_indices = [0,1,2]
col_indices = [0,1,2]
arr[row_indices, col_indices]

array([1, 5, 9])

#### - Selection
- Using brackets for selection based off of comparison operators (< > =)

In [511]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [512]:
# based on the comparison operators
# returns the array of booleans for each element
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [513]:
arr[arr > 4] # returns the array of elements that are true for the comparison

array([ 5,  6,  7,  8,  9, 10])

In [514]:
arr[arr <= 3]

array([1, 2, 3])

#### - Broadcasting
- Numpy arrays differ from a normal Python list because of their ability to broadcast
- Broadcasting allows Numpy to vectorize operations across arrays with different but compatible shapes

##### Example 1: Scalar and Array

In [519]:
arr = np.array([1,2,3])
incre = 10

result = arr + incre # broadcasting scalar 10 to [10, 10, 10]
print(result)

[11 12 13]


##### Example 2: 2D and 1D Array

In [520]:
a = np.array([[1,2,3], 
              [4,5,6]]) # shpae: (2, 3)
b = np.array([10, 20, 30]) # shape: (3,)

# since a has 2 rows,
# b is broadcasting to shape (2, 3):
# [[10, 20, 30],
#  [10, 20, 30]]
result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


##### Example 3: Incompatible Shapes (Error)

In [521]:
a = np.array([1,2,3])
b = np.array([[1], [2]])

# b broadcasting to [[1,1,1], [2,2,2]]
result = a + b
print(result)

[[2 3 4]
 [3 4 5]]


### Numpy Operations
#### - Arithmetic: addition, subtraction, multiplication, division

In [522]:
arr = np.array([1,2,3,4,5])

In [523]:
arr + arr

array([ 2,  4,  6,  8, 10])

In [524]:
arr - arr

array([0, 0, 0, 0, 0])

In [525]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [526]:
arr / arr

array([1., 1., 1., 1., 1.])

In [527]:
arr * 3

array([ 3,  6,  9, 12, 15])

#### - Universal Array Functions

In [528]:
arr = np.array([1,4,9,16,25])
np.sqrt(arr) # taking square roots

array([1., 2., 3., 4., 5.])

In [529]:
np.exp(arr) # calculating exponential e^

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10])

In [530]:
print(np.max(arr)) # same as arr.max()

25


In [531]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175])

In [532]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582])